# Generated by Django 3.1.1 on 2020-09-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.continent')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pincode', models.IntegerField()),
                ('website', models.CharField(max_length=255)),
                ('districtorcity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.district')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.country')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.language')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.venue')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='continent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.state'),
        ),
        migrations.AddField(
            model_name='album',
            name='recordlabel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.recordlabel'),
        ),
    ]
