# Generated by Django 3.1.1 on 2020-09-20 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20200920_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalUserDetails',
            new_name='AdditionalArtistDetails',
        ),
    ]
