# Generated by Django 3.1.1 on 2020-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200920_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalartistdetails',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
