# Generated by Django 3.1.1 on 2020-09-21 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20200921_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalartistdetail',
            name='is_artist',
        ),
        migrations.CreateModel(
            name='AdditionalStudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
